### ISSUE TITLE
Potential Issues in Glyphs 3.2

### ISSUE THREAD

**Issue by maciej-nadobnik** [moontypespace/NodesCloseToZones-Glyphs#3]
Hi @moontypespace,

This plugin continues to be the best tool I know for checking proper setting of alignment zones – thanks! It looks like recent Glyphs updates may have caused some issues. After updating to G 3.2 I no longer can see the red markers and the _New Tab with Nodes Close To Zones_ option now opens a tab with slashed glyphs names e.g. /aacute instead of the actual affected layers as before. Please find some screenshots and the test source (Montserrat).

Best,
Maciej

Test source:
https://github.com/JulietaUla/Montserrat/blob/master/sources/Montserrat.glyphs

<img width="1346" alt="Screenshot 2023-01-23 at 18 19 00" src="https://user-images.githubusercontent.com/21235430/214107004-802c69c2-24e0-49d8-a23e-353d4d22282c.png">
<img width="1862" alt="Screenshot 2023-01-23 at 18 15 21" src="https://user-images.githubusercontent.com/21235430/214107036-c9b17305-4e1e-4bb3-9256-66e44caedee7.png">
<img width="572" alt="Screenshot 2023-01-23 at 18 15 40" src="https://user-images.githubusercontent.com/21235430/214107047-5c18a9ba-4732-4e66-af2b-e27c96ba4290.png">

**Comment by schriftgestalt** [comment]
The red triangle don’t show for me in version 3.1.2 either. And the "New Tab…" is fixed in version 3172.

**Comment by maciej-nadobnik** [comment]
Hi @schriftgestalt, thanks for answering. I have just updated to 3173 and the issue persists (using the same source file for testing). Could it be a problem with my installation?
<img width="1646" alt="Screenshot 2023-01-24 at 12 39 52" src="https://user-images.githubusercontent.com/21235430/214282627-df389d6f-44d5-4b4b-a333-2c5040c5803b.png">
<img width="572" alt="Screenshot 2023-01-24 at 12 40 07" src="https://user-images.githubusercontent.com/21235430/214282659-6986dbf2-5dbd-4cb1-b154-053c0967cd5f.png">

**Comment by schriftgestalt** [comment]
<img width="968" alt="Bildschirmfoto 2023-01-24 um 14 53 54" src="https://user-images.githubusercontent.com/174660/214312811-9d02375b-d07f-4aa9-9875-68b340939e45.png">
Works for me. 

Do you see anything in the Macro window?

**Comment by maciej-nadobnik** [comment]
Strange. I don’t see the triangles and the _New Tab..._ still shows slashed glyph names. I don’t see any messages in the macro panel after opening the new tab.

**Comment by schriftgestalt** [comment]
What python version do you have?

**Comment by maciej-nadobnik** [comment]
For system default installation I have 2.7.18. After updating to Monterey I replaced the default Python with 2.7 in order to run Glyphs 2. The In-app setting says 3.9.1.
<img width="697" alt="Screenshot 2023-01-25 at 13 57 17" src="https://user-images.githubusercontent.com/21235430/214570245-5ee89875-e393-4651-b44f-6a30072da0c8.png">
<img width="776" alt="Screenshot 2023-01-25 at 13 58 31" src="https://user-images.githubusercontent.com/21235430/214570241-5b070f4d-94fb-45ae-922e-981117b64e21.png">

**Comment by schriftgestalt** [comment]
Can you try to remove all other plugins?

**Comment by maciej-nadobnik** [comment]
Ok, will do

**Comment by ollimeier** [comment]
@maciej-nadobnik and @schriftgestalt It does not work for for me either:
<img width="1504" alt="Screenshot 2023-01-25 at 17 55 31" src="https://user-images.githubusercontent.com/21055547/214628323-d53edd9c-1dab-4531-90bc-a81c93fafb4b.png">

As it used to work in a previous version of Glyphs, I would expect Georg has changed something, but I am not sure what it is.

**Comment by ollimeier** [comment]
In general the plugin seems to work. I get the 'Text' and also the 'red arrows' (as you can see in the screenshot above). But the 'new tab' function is kind of broken. Some glyphs have a style, some don't. @schriftgestalt Is there anything you have changed when it comes to 'new tabs formatting'?

**Comment by schriftgestalt** [comment]
Das "new Tab" problem habe ich repariert. 

> @maciej-nadobnik and @schriftgestalt It does not work for for me either:

But the red triangles are in your screenshot. Only very small. That is how it was for me in all versions.

**Comment by maciej-nadobnik** [comment]
Hi @schriftgestalt and @moontypespace

I checked again today and realised that the arrows and text do appear for me, but selectively. For example, they do appear at the misaligned stem nodes of /aogonek.loclNAV.sc.ss01, but not for its misaligned ogonek accent (I modified it to sit at the same height as the stem):

<img width="1298" alt="Screenshot 2023-01-26 at 12 58 25" src="https://user-images.githubusercontent.com/21235430/214829940-5e9c5fdb-7f8b-4355-941d-f4c721ee7d83.png">

Similarly I get no marking for nodes close to the Smallcap zone:

<img width="1158" alt="Screenshot 2023-01-26 at 12 57 20" src="https://user-images.githubusercontent.com/21235430/214829961-aa00a4d6-6bfb-4145-8217-6af9184548df.png">

I have tested this on the latest Glyphs (3175) and the latest stable version (3151) with only Nodes Close To Zones installed. The marking of nodes behaves in the same way in both versions. That would be a Plugin thing, but I am sure there is logic behind showing/not showing the error, at least in case of the stem/ogonek case.

What _is_ different between 3151 and 3175 is that the _New Tab..._ works fine in 3151, so there could be a Glyphs-related change behind the problem.

**Comment by ollimeier** [comment]
@maciej-nadobnik Excuse me very much for the late response. But finally I had the chance to look into it and hopefully to fix it as well. Please let me know if it works for you as well. Thanks a lot in advance.

**Comment by maciej-nadobnik** [comment]
Hi @moontypespace, I have just checked on 3.2 (3194) and it works great again! Thanks so much for fixing!

**Comment by glenda-tn** [comment]
Thanks for fixing this @moontypespace! Confirmed it’s working again for me, too Glyphs 3.2 (3193) — oh, I see there is an update! :)
